const $ = (selector, scope = document) => scope.querySelector(selector);
const $$ = (selector, scope = document) => [...scope.querySelectorAll(selector)];
const isGitHubPages = location.hostname.endsWith(".github.io");

const grammarExercises = [
  { question: "If I had more time, I ___ travelling around the world.", options: ["would go", "will go", "go", "went"], answer: 0, rule: "Second Conditional", explanation: "Для нереальной или маловероятной ситуации используем If + Past Simple, would + base verb. Здесь: If I had more time, I would go travelling.", example: "If I had more money, I would buy a house." },
  { question: "She ___ to school by bus every day.", options: ["go", "goes", "is going", "went"], answer: 1, rule: "Present Simple", explanation: "Слова every day указывают на привычное действие. В третьем лице единственного числа к глаголу добавляется -s: she goes.", example: "He plays football every weekend." },
  { question: "By next summer, they ___ the project.", options: ["finish", "will finish", "will have finished", "finished"], answer: 2, rule: "Future Perfect", explanation: "By next summer обозначает результат к моменту в будущем. Используем will have + V3: will have finished.", example: "By 2030, I will have graduated." }
];
const words = [
  { word:"significant", pronunciation:"/sɪɡˈnɪfɪkənt/", translation:{ru:"значительный, важный",kz:"маңызды, елеулі"}, example:"This is a significant change in his life.", synonyms:["important","considerable","meaningful","notable"], quiz:"The discovery was ___ for the future of science.", options:["significant","similar","different","normal"], answer:0, extras:[["opportunity","шанс, возможность","мүмкіндік"],["challenge","сложная задача","күрделі міндет"],["progress","развитие, прогресс","даму, ілгерілеу"],["environment","окружающая среда","қоршаған орта"]] },
  { word:"achieve", pronunciation:"/əˈtʃiːv/", translation:{ru:"достигать",kz:"қол жеткізу"}, example:"She achieved her goal after months of practice.", synonyms:["reach","attain","accomplish","fulfil"], quiz:"With daily practice, you can ___ better results.", options:["achieve","avoid","forget","borrow"], answer:0, extras:[["confident","уверенный","сенімді"],["improve","улучшать","жақсарту"],["attempt","попытка","талпыныс"],["feedback","обратная связь","кері байланыс"]] },
  { word:"reliable", pronunciation:"/rɪˈlaɪəbəl/", translation:{ru:"надёжный",kz:"сенімді"}, example:"A reliable friend always keeps their promises.", synonyms:["dependable","trustworthy","steady","consistent"], quiz:"Use a ___ source when you do research.", options:["reliable","noisy","empty","temporary"], answer:0, extras:[["evidence","доказательство","дәлел"],["opinion","мнение","пікір"],["support","поддержка","қолдау"],["solution","решение","шешім"]] }
];
const state = { view:"home", grammarIndex:0, currentGrammar:null, selectedGrammar:null, grammarChecked:false, wordIndex:0, currentWord:null, selectedVocab:null, vocabularyChecked:false, vocabularyPractice:[], vocabularyStep:0, writingType:"Essay", writingFeedback:"", keepListening:false, exerciseTokens:{}, taskLevels:{}, level:"A1", language:localStorage.getItem("fluentpath-language") || "ru", progress:{ completed:0, writingAnalyses:0, speakingSessions:0, vocabularyWords:0, streak:0, level:"A1", levelProgress:0, skillLevels:{grammar:"A1",vocabulary:"A1",writing:"A1",speaking:"A1"}, profile:{name:"Ученик",avatar:"А"}, skills:{grammar:0,vocabulary:0,writing:0,speaking:0} }, recognition:null };

const ui = { ru:{
  "Главная":"Главная","Grammar":"Grammar","Vocabulary":"Vocabulary","Writing":"Writing","Speaking":"Speaking","AI Tutor":"AI Tutor","Progress":"Progress","Ученик":"Ученик","Выберите уровень":"Выберите уровень","Твой личный":"Твой личный","репетитор.":"репетитор.","Спроси о любом правиле простыми словами.":"Спроси о любом правиле простыми словами.","ПОПРОБУЙТЕ СПРОСИТЬ":"ПОПРОБУЙТЕ СПРОСИТЬ","Проверить":"Проверить","Другое задание":"Другое задание","Я запомнил(а)":"Я запомнил(а)","БЫСТРЫЙ КВИЗ":"БЫСТРЫЙ КВИЗ","Следующее слово →":"Следующее слово →","Ещё слова для тебя":"Ещё слова для тебя","Слова, которые":"Слова, которые","оста́нутся с тобой.":"оста́нутся с тобой.","Запоминай слово в контексте, а не отдельным переводом.":"Запоминай слово в контексте, а не отдельным переводом." }, kz:{
  "Главная":"Басты бет","Grammar":"Грамматика","Vocabulary":"Сөздік","Writing":"Жазылым","Speaking":"Сөйлеу","AI Tutor":"AI оқытушы","Progress":"Прогресс","Ученик":"Оқушы","Выберите уровень":"Деңгейді таңдаңыз","Твой личный":"Жеке","репетитор.":"оқытушың.","Спроси о любом правиле простыми словами.":"Кез келген ережені қарапайым тілмен сұраңыз.","ПОПРОБУЙТЕ СПРОСИТЬ":"СҰРАП КӨРІҢІЗ","Проверить":"Тексеру","Другое задание":"Басқа тапсырма","Я запомнил(а)":"Есте сақтадым","БЫСТРЫЙ КВИЗ":"ЖЫЛДАМ ТЕСТ","Следующее слово →":"Келесі сөз →","Ещё слова для тебя":"Сізге тағы сөздер","Слова, которые":"Сізбен бірге","оста́нутся с тобой.":"қалатын сөздер.","Запоминай слово в контексте, а не отдельным переводом.":"Сөзді жеке аудармамен емес, контексте есте сақтаңыз." } };
Object.assign(ui.kz, {
  "Грамматика":"Грамматика","Слова":"Сөздер","Письмо":"Жазылым","Речь":"Сөйлеу","AI-репетитор":"AI оқытушы","Прогресс":"Прогресс",
  "YOUR AI ENGLISH TUTOR":"СІЗДІҢ AI АҒЫЛШЫН ТІЛІ ОҚЫТУШЫҢЫЗ","Английский, который":"Сізге бейімделген","подстраивается под тебя.":"ағылшын тілі.","Практикуйся регулярно, получай понятные объяснения и видь свой прогресс.":"Тұрақты жаттығып, түсінікті түсіндірме алып, прогресті бақылаңыз.","Начать занятие":"Сабақты бастау","Твоя учебная панель":"Оқу панеліңіз","Выбери навык — начнём с короткой практики.":"Дағдыны таңдаңыз — қысқа жаттығудан бастаймыз.","Весь прогресс →":"Барлық прогресс →","Правила, примеры и задания с объяснением ошибок.":"Ережелер, мысалдар және қателер түсіндірмесі бар тапсырмалар.","Практиковать →":"Жаттығу →","Полезные слова, синонимы и короткие квизы.":"Пайдалы сөздер, синонимдер және қысқа тесттер.","Учить слова →":"Сөз үйрену →","Пиши тексты и получай развёрнутую AI-проверку.":"Мәтін жазыңыз және толық AI тексерісін алыңыз.","Проверить текст →":"Мәтінді тексеру →","Отвечай на вопросы и развивай уверенную речь.":"Сұрақтарға жауап беріп, сенімді сөйлеуді дамытыңыз.","Начать диалог →":"Диалогты бастау →","Твой уровень":"Деңгейіңіз","Твоя серия":"Серияңыз","дней подряд":"күн қатарынан","Понимай правила,":"Ережелерді түсін,","а не угадывай.":"болжаушы болма.","Выбери ответ — после проверки увидишь объяснение.":"Жауапты таңдаңыз — тексеруден кейін түсіндірмені көресіз.","ЗАДАНИЕ":"ТАПСЫРМА","Слово дня":"Күн сөзі","Сегодня":"Бүгін","СИНОНИМЫ":"СИНОНИМДЕР","Пиши. Получай":"Жаз. Кері байланыс","обратную связь. Расти.":"ал. Дамы.","AI найдёт ошибки и подскажет, как сделать текст сильнее.":"AI қателерді тауып, мәтінді қалай күшейту керегін ұсынады.","Практикуй":"Шынайы","настоящую речь.":"сөйлеуді жаттықтыр.","Отвечай голосом или текстом — AI даст аккуратную обратную связь.":"Дауыспен не мәтінмен жауап беріңіз — AI нақты кері байланыс береді.","Твои маленькие":"Кішкентай","победы складываются.":"жеңістеріңіз жиналады.","Смотри не только на количество заданий, но и на навыки, которые укрепляешь.":"Тек тапсырма санын емес, дамытып жатқан дағдыларыңызды да бақылаңыз."
});
Object.assign(ui.ru, { "Grammar":"Грамматика","Vocabulary":"Слова","Writing":"Письмо","Speaking":"Речь","AI Tutor":"AI-репетитор","Progress":"Прогресс","Грамматика":"Грамматика","Слова":"Слова","Письмо":"Письмо","Речь":"Речь","AI-репетитор":"AI-репетитор","Прогресс":"Прогресс" });
Object.assign(ui.kz, { "останутся с тобой.":"қалатын сөздер." });
Object.assign(ui.ru, { "останутся с тобой.":"останутся с тобой." });
// Старое написание со знаком ударения не должно возвращаться при смене языка.
delete ui.ru["оста́нутся с тобой."];
delete ui.kz["оста́нутся с тобой."];
Object.keys(ui.kz).forEach((key) => { if (!ui.ru[key]) ui.ru[key] = key; });
function tr(value) { return state.language === "kz" ? (ui.kz[value] || value) : (ui.ru[value] || value); }
function translateStaticText() { const map = ui[state.language]; const source = state.language === "kz" ? ui.ru : ui.kz; const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode); nodes.forEach((node) => { const original = node.nodeValue.trim(); const canonical = Object.entries(source).find(([, value]) => value === original)?.[0] || original; if (map[canonical]) node.nodeValue = node.nodeValue.replace(original, map[canonical]); }); document.documentElement.lang = state.language === "kz" ? "kk" : "ru"; }
function applyLanguage(language) { state.language = language === "kz" ? "kz" : "ru"; localStorage.setItem("fluentpath-language", state.language); $("#language-toggle").textContent = state.language.toUpperCase(); translateStaticText(); const placeholders = state.language === "kz" ? {"#tutor-input":"Ағылшын тілі туралы сұрақ қойыңыз…","#writing-input":"Эссені ағылшын тілінде осында жазыңыз…","#speaking-input":"Жазбаны бастау түймесін басып, микрофонға рұқсат беріңіз."} : {"#tutor-input":"Спроси что-нибудь об английском…","#writing-input":"Напишите эссе на английском здесь…","#speaking-input":"Нажми «Начать запись», разреши доступ к микрофону и говори по-английски."}; Object.entries(placeholders).forEach(([selector,value]) => { const field = $(selector); if (field) field.placeholder = value; }); syncProgressUI(); updateProgressWidgets(); renderProgress(); }

function escapeHtml(value) { return String(value || "").replace(/[&<>"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"})[char]); }
function paragraphize(text) { return escapeHtml(text).split(/\n{2,}/).map(block => `<p>${block.replace(/\n/g,"<br>")}</p>`).join(""); }
function scoreFromFeedback(text, fallback = 50) { const match = String(text).match(/Оценка\s*(?:уровня)?\s*:\s*(\d{1,3})\s*\/\s*100/i); return match ? Math.max(0, Math.min(100, Number(match[1]))) : fallback; }
function setView(name) { state.view = name; $$(".view").forEach(view => view.classList.toggle("active", view.id === `${name}-view`)); $$(".nav-link").forEach(button => button.classList.toggle("active", button.dataset.view === name)); $("#crumb").textContent = {home:"Главная",grammar:"Grammar",vocabulary:"Vocabulary",writing:"Writing",speaking:"Speaking",tutor:"AI Tutor",progress:"Progress"}[name]; window.scrollTo({ top:0, behavior:"smooth" }); if (name === "progress") renderProgress(); if (["grammar","vocabulary","writing","speaking"].includes(name)) loadExercise(name); }
function renderAvatar(selector, fallback) { const target = $(selector); const image = localStorage.getItem("fluentpath-avatar-image"); target.replaceChildren(); if (image?.startsWith("data:image/")) { const avatar = document.createElement("img"); avatar.src = image; avatar.alt = "Аватар профиля"; target.append(avatar); } else target.textContent = fallback || "А"; }
function showToast(message) { const toast = $("#app-toast"); toast.textContent = `✓ ${message}`; toast.classList.add("show"); clearTimeout(state.toastTimer); state.toastTimer = setTimeout(() => toast.classList.remove("show"), 3200); }
function renderProfilePreview(fallback) { const target = $("#current-avatar-preview"); const image = state.usePresetAvatar ? "" : (state.pendingAvatarImage || localStorage.getItem("fluentpath-avatar-image")); target.replaceChildren(); if (image?.startsWith("data:image/")) { const avatar = document.createElement("img"); avatar.src = image; avatar.alt = "Выбранная аватарка"; target.append(avatar); } else target.textContent = fallback || "А"; }
function syncProgressUI() { const names = state.language === "kz" ? {A1:"Бастапқы",A2:"Негізгі",B1:"Орта",B2:"Ортадан жоғары",C1:"Жоғары",C2:"Еркін"} : {A1:"Начальный",A2:"Базовый",B1:"Средний",B2:"Выше среднего",C1:"Продвинутый",C2:"Свободное владение"}; state.level = state.progress.level || "A1"; const profile = state.progress.profile || {name:"Ученик",avatar:"А"}; const levelLabel = `${state.level} · ${names[state.level]}`; $("#sidebar-level").textContent = `AI · ${levelLabel}`; $("#home-level-orb").textContent = state.level; $("#home-level-summary").textContent = levelLabel; const label = document.querySelector(".level-label"); if (label) label.textContent = levelLabel; $("#level-bar").style.width = `${state.progress.levelProgress || 0}%`; $("#level-bar-summary").style.width = `${state.progress.levelProgress || 0}%`; const note = ["C1", "C2"].includes(state.level) ? "Максимальный уровень достигнут." : `До следующего уровня: ${state.progress.levelProgress || 0}%`; $("#level-note").textContent = note; $("#level-note-summary").textContent = ["C1", "C2"].includes(state.level) ? "Максимальный уровень достигнут." : "Выполняй задания — уровень повысится автоматически."; $("#streak-number-summary").textContent = state.progress.streak || 0; $("#sidebar-name").textContent = profile.name || "Ученик"; renderAvatar("#sidebar-avatar", profile.avatar); renderAvatar("#top-avatar", profile.avatar); $("#grammar-level").textContent = state.taskLevels.grammar || state.progress.skillLevels?.grammar || "A1"; }
function renderGrammar() { const task = state.currentGrammar || grammarExercises[state.grammarIndex]; const kz = state.language === "kz"; const level = state.taskLevels.grammar || state.progress.skillLevels?.grammar || "A1"; $("#grammar-count").textContent = level; $("#grammar-level").textContent = level; $("#grammar-question").textContent = task.question; const answers = $("#grammar-answers"); answers.replaceChildren(); task.options.forEach((option, index) => { const button = document.createElement("button"); button.type = "button"; button.className = "answer"; button.innerHTML = `<span>${"ABCD"[index]}</span>${escapeHtml(option)}`; button.addEventListener("click", () => { if (state.grammarChecked) return; state.selectedGrammar = index; $$(".answer", answers).forEach((item, itemIndex) => item.classList.toggle("selected", itemIndex === index)); checkGrammarAnswer(); }); answers.append(button); }); $("#grammar-feedback").className = "feedback-card empty"; $("#grammar-feedback").innerHTML = `<span class="feedback-symbol">✦</span><h3>${kz ? "Тексеруге дайынсыз ба?" : "Готов к проверке?"}</h3><p>${kz ? "Бір жауапты таңдаңыз, ережені қарапайым тілмен түсіндіремін." : "Выбери один вариант, и я объясню правило простыми словами."}</p>`; $("#check-grammar").disabled = false; state.selectedGrammar = null; state.grammarChecked = false; }
async function registerProgress(type, score) { const saveLocally = () => { const local = state.progress; local.completed += 1; if (type === "writing") local.writingAnalyses += 1; if (type === "speaking") local.speakingSessions += 1; if (type === "vocabulary") local.vocabularyWords += 1; local.streak = Math.max(1, local.streak); local.skills[type] = Math.round(Math.min(100, local.skills[type] * .7 + score * .3)); localStorage.setItem("fluentpath-progress", JSON.stringify(local)); }; if (isGitHubPages) saveLocally(); else { try { const response = await fetch("/api/progress", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({type,score}) }); if (!response.ok) throw new Error(); const data = await response.json(); state.progress = data.progress; } catch { saveLocally(); } } syncProgressUI(); updateProgressWidgets(); }
function updateProgressWidgets() { const names = state.language === "kz" ? {A1:"Бастапқы",A2:"Негізгі",B1:"Орта",B2:"Ортадан жоғары",C1:"Жоғары",C2:"Еркін"} : {A1:"Начальный",A2:"Базовый",B1:"Средний",B2:"Выше среднего",C1:"Продвинутый",C2:"Свободное владение"}; const level = state.progress.level || "A1"; const levelLabel = `${level} · ${names[level] || ""}`; $("#streak-number").textContent = state.progress.streak || 0; $("#streak-number-summary").textContent = state.progress.streak || 0; $("#progress-streak").textContent = state.progress.streak || 0; $("#home-level-orb").textContent = level; $("#home-level-summary").textContent = levelLabel; const label = document.querySelector(".level-label"); if (label) label.textContent = levelLabel; }
function shuffle(items) { const result = [...items]; for (let index = result.length - 1; index > 0; index -= 1) { const swap = Math.floor(Math.random() * (index + 1)); [result[index], result[swap]] = [result[swap], result[index]]; } return result; }
function buildVocabularyPractice(word) { const otherWords = shuffle(words.filter(item => item.word !== word.word)).slice(0,3); const targetTranslation = state.language === "kz" ? word.translation.kz : word.translation.ru; const translationChoices = shuffle([{text:targetTranslation,correct:true}, ...otherWords.map(item => ({text:state.language === "kz" ? item.translation.kz : item.translation.ru,correct:false}))]); const wordChoices = shuffle([{text:word.word,correct:true}, ...otherWords.map(item => ({text:item.word,correct:false}))]); const fillChoices = shuffle(word.options.map((text,index) => ({text,correct:index === word.answer}))); return [{ question:word.quiz, options:fillChoices, answerLabel:"Выбери подходящее слово в контексте." }, { question:`Как переводится слово “${word.word}”?`, options:translationChoices, answerLabel:"Соедини английское слово с его значением." }, { question:`Какое английское слово означает: «${targetTranslation}»?`, options:wordChoices, answerLabel:"Вспомни английское слово по его переводу." }]; }
function renderVocabularyPractice() { const practice = state.vocabularyPractice[state.vocabularyStep]; if (!practice) return; $("#vocabulary-count").textContent = `${state.vocabularyStep + 1} / ${state.vocabularyPractice.length}`; $("#vocabulary-question").textContent = practice.question; const answers = $("#vocabulary-answers"); answers.replaceChildren(); practice.options.forEach((option,index) => { const button = document.createElement("button"); button.className = "mini-answer"; button.textContent = `${"ABCD"[index]}. ${option.text}`; button.addEventListener("click", () => { if (state.vocabularyChecked) return; state.selectedVocab = index; $$(".mini-answer",answers).forEach((entry,i)=>entry.classList.toggle("selected",i===index)); }); answers.append(button); }); $("#vocabulary-feedback").textContent = practice.answerLabel; $("#check-vocabulary").disabled = false; $("#next-vocabulary-task").hidden = true; state.selectedVocab = null; state.vocabularyChecked = false; }
function renderVocabulary() { const rawWord = state.currentWord || words[state.wordIndex]; const word = rawWord.translation ? rawWord : { ...rawWord, translation:{ru:rawWord.translationRu,kz:rawWord.translationKz} }; const kz = state.language === "kz"; $("#vocabulary-view").classList.remove("practice-mode"); $("#learn-word").innerHTML = "Начать 3 задания <span>→</span>"; $("#word-name").textContent = word.word; $("#word-pronunciation").textContent = word.pronunciation || ""; $("#word-translation").innerHTML = `<strong>${kz ? "Қазақша:" : "Русский:"}</strong> ${escapeHtml(kz ? word.translation.kz : word.translation.ru)}<small>${kz ? "Орысша" : "Қазақша"}: ${escapeHtml(kz ? word.translation.ru : word.translation.kz)}</small>`; $("#word-example").textContent = `“${word.example}”`; $("#synonyms").innerHTML = word.synonyms.map(item => `<span>${item}</span>`).join(""); $("#word-list").innerHTML = word.extras.map(([name,ru,kzValue]) => `<article class="small-word"><strong>${name}</strong><span>${kz ? kzValue : ru}<br /><em>${kz ? ru : kzValue}</em></span></article>`).join(""); state.vocabularyPractice = buildVocabularyPractice(word); state.vocabularyStep = 0; renderVocabularyPractice(); }
function renderProgress() { const progress = state.progress; $("#completed-stat").textContent = progress.completed || 0; $("#writing-stat").textContent = progress.writingAnalyses || 0; $("#speaking-stat").textContent = progress.speakingSessions || 0; $("#vocabulary-stat").textContent = progress.vocabularyWords || 0; $("#progress-streak").textContent = progress.streak || 0; const labels = {grammar:"Grammar",vocabulary:"Vocabulary",writing:"Writing",speaking:"Speaking"}; const colors = {grammar:"#4d91f4",vocabulary:"#8467ed",writing:"#ff9a62",speaking:"#24b98c"}; const emptyColor = "#e3e8f1"; const entries = Object.entries(labels).map(([key,label]) => ({key,label,value:Math.max(0,Math.min(100,Number(progress.skills?.[key]) || 0))})); const average = Math.round(entries.reduce((sum,item) => sum + item.value, 0) / entries.length); const segments = entries.flatMap((item,index) => { const start = index * 90; const filled = start + item.value * .9; const end = start + 90; return [`${item.value ? colors[item.key] : emptyColor} ${start.toFixed(1)}deg ${filled.toFixed(1)}deg`, `${emptyColor} ${filled.toFixed(1)}deg ${end.toFixed(1)}deg`]; }); $("#skills-chart").style.background = `conic-gradient(${segments.join(",")})`; $("#skills-average").textContent = `${average}%`; $("#skills-chart").setAttribute("aria-label", `Общий прогресс: ${average} процентов`); $("#skills-legend").innerHTML = entries.map((item) => `<div class="${item.value ? "" : "unstarted"}" style="--chart-color:${item.value ? colors[item.key] : emptyColor}"><i></i><b>${item.label}</b><span>${item.value}%</span></div>`).join(""); $("#skill-bars").innerHTML = entries.map((item) => `<div class="skill-bar ${item.value ? "" : "unstarted"}"><b>${item.label}</b><div><i style="width:${item.value}%"></i></div><span>${item.value}%</span></div>`).join(""); }
async function getProgress() { if (isGitHubPages) { try { state.progress = { ...state.progress, ...JSON.parse(localStorage.getItem("fluentpath-progress") || "{}") }; } catch {} $("#api-note").textContent = "Статическая версия: прогресс хранится в этом браузере. Для AI-функций нужен отдельный сервер."; } else { try { const response = await fetch("/api/progress"); if (!response.ok) throw new Error(); state.progress = (await response.json()).progress; $("#api-note").textContent = "AI Tutor готов. Ваш прогресс сохраняется локально на этом компьютере."; } catch { try { state.progress = { ...state.progress, ...JSON.parse(localStorage.getItem("fluentpath-progress") || "{}") }; } catch {} } } syncProgressUI(); updateProgressWidgets(); }
async function askAi(prompt) { if (isGitHubPages) throw new Error("AI Tutor доступен в полной версии сайта с Node.js API. GitHub Pages размещает только интерфейс."); const response = await fetch("/api/tutor", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({prompt}) }); if (!response.ok) { const error = await response.json().catch(()=>({})); throw new Error(error.error || "AI пока недоступен."); } return (await response.json()).answer; }
function exerciseButton(kind) { return $(kind === "grammar" ? "#next-grammar" : kind === "vocabulary" ? "#next-word" : kind === "writing" ? "#next-writing" : "#next-speaking"); }
function showExercise(kind, exercise) { if (kind === "grammar") { state.currentGrammar = exercise; renderGrammar(); } if (kind === "vocabulary") { state.currentWord = exercise; renderVocabulary(); } if (kind === "writing") { $("#writing-topic").textContent = exercise.topic; $("#writing-type").textContent = exercise.type || "WRITING"; $("#writing-hint").textContent = exercise.hint || ""; } if (kind === "speaking") { $("#speaking-question").textContent = exercise.question; $("#speaking-hint").textContent = exercise.hint || "Ответьте по-английски. Старайтесь использовать 3–5 предложений."; $("#speaking-input").value = ""; } }
const writingFormats = { Essay:{ type:"ESSAY", topic:"Should schools give students less homework? Give your opinion and support it with reasons.", hint:"Напиши вступление, 2 аргумента и короткий вывод." }, Email:{ type:"EMAIL", topic:"Write an email to your English teacher asking for advice about preparing for an exam.", hint:"Используй приветствие, цель письма, вопросы и вежливое завершение." }, Report:{ type:"REPORT", topic:"Write a short report about students' favourite after-school activities at your school.", hint:"Добавь заголовок, факты, вывод и одну рекомендацию." } };
function selectWritingType(type) { const format = writingFormats[type]; if (!format) return; state.writingType = type; $$("#writing-modes button").forEach(button => button.classList.toggle("selected", button.dataset.writingType === type)); $("#writing-type").textContent = format.type; $("#writing-topic").textContent = format.topic; $("#writing-hint").textContent = format.hint; $("#writing-input").value = ""; $("#word-count").textContent = "0 / 400 слов"; }
function renderWritingFeedback(tab) { const answer = state.writingFeedback; if (!answer) return; const errors = answer.match(/Ошибки:\s*([\s\S]*?)(?=Улучшенная версия:|Оценка уровня:|$)/i)?.[1]?.trim() || "AI не нашёл отдельный список ошибок."; const text = tab === "errors" ? `Ошибки:\n${errors}` : answer; setAiResult("#writing-result", "", `<span class="feedback-symbol">✓</span><h3>${tab === "errors" ? "Ошибки и исправления" : "Твой персональный отзыв"}</h3>${paragraphize(text)}`); }
async function loadExercise(kind) {
  const token = (state.exerciseTokens[kind] || 0) + 1; state.exerciseTokens[kind] = token;
  const button = exerciseButton(kind); if (button) { button.disabled = true; button.setAttribute("aria-busy", "true"); }
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 2500);
  try {
    if (isGitHubPages) {
      let exercise;
      if (kind === "grammar") { exercise = grammarExercises[state.grammarIndex % grammarExercises.length]; state.grammarIndex = (state.grammarIndex + 1) % grammarExercises.length; }
      else if (kind === "vocabulary") { exercise = words[state.wordIndex % words.length]; state.wordIndex = (state.wordIndex + 1) % words.length; }
      else if (kind === "writing") { const formats = Object.values(writingFormats); exercise = formats[Math.floor(Math.random() * formats.length)]; }
      else if (kind === "speaking") { const questions = ["What do you usually do in your free time?", "Describe a place you enjoy visiting.", "What skill would you like to learn, and why?", "Tell me about a book or film you enjoyed."]; exercise = { question:questions[Math.floor(Math.random() * questions.length)], hint:"Ответьте по-английски. Старайтесь сказать 3–5 предложений." }; }
      if (!exercise) throw new Error("Не удалось подобрать задание.");
      state.taskLevels[kind] = state.progress.skillLevels?.[kind] || "A1";
      showExercise(kind, exercise);
      return;
    }
    const response = await fetch("/api/exercises", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ kind }), signal:controller.signal });
    if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || "Не удалось загрузить задание.");
    const { exercise, level } = await response.json();
    if (!exercise) throw new Error("В базе пока нет задания. Попробуйте ещё раз.");
    if (state.exerciseTokens[kind] !== token) return;
    state.taskLevels[kind] = level || state.progress.skillLevels?.[kind] || "A1";
    showExercise(kind, exercise);
  } catch (error) {
    if (state.exerciseTokens[kind] !== token) return;
    if (kind === "grammar") { state.currentGrammar = null; state.grammarIndex = (state.grammarIndex + 1) % grammarExercises.length; renderGrammar(); }
    if (kind === "vocabulary") { state.currentWord = null; state.wordIndex = (state.wordIndex + 1) % words.length; renderVocabulary(); }
    if (kind === "writing") $("#writing-hint").textContent = error.message;
    if (kind === "speaking") $("#speaking-hint").textContent = error.message;
  } finally { clearTimeout(timeout); if (state.exerciseTokens[kind] === token && button) { button.disabled = false; button.removeAttribute("aria-busy"); } }
}
function setAiResult(selector, stateName, html) { const target = $(selector); target.className = `ai-result ${stateName || ""}`; target.innerHTML = html; }
async function prepareMicrophone() { if (!navigator.mediaDevices?.getUserMedia) throw new Error("Браузер не поддерживает доступ к микрофону."); state.micStream?.getTracks().forEach(track => track.stop()); const selected = $("#microphone-device").value; const stream = await navigator.mediaDevices.getUserMedia({ audio:selected ? { deviceId:{ exact:selected } } : true }); const track = stream.getAudioTracks()[0]; if (!track) throw new Error("Выбранный микрофон не передаёт аудио."); state.micStream = stream; state.micTrack = track; const devices = await navigator.mediaDevices.enumerateDevices(); const microphones = devices.filter(device => device.kind === "audioinput"); if (!microphones.length) throw new Error("Микрофоны не найдены. Подключите устройство и повторите."); const select = $("#microphone-device"); select.replaceChildren(...microphones.map((device,index) => { const option = document.createElement("option"); option.value = device.deviceId; option.textContent = device.label || `Микрофон ${index + 1}`; option.selected = device.deviceId === selected || (!selected && device.deviceId === track.getSettings().deviceId); return option; })); }
function initSpeakingRecognition() { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) throw new Error("В этом браузере нет распознавания речи. Откройте сайт в Chrome или Edge."); if (state.recognition) return; state.recognition = new Recognition(); state.recognition.lang = "en-US"; state.recognition.interimResults = true; state.recognition.continuous = true; state.recognition.onstart = () => { $("#microphone").classList.add("recording"); $("#record-speaking").textContent = "■ Остановить запись"; $("#recording-status").textContent = "Слушаю английскую речь через выбранный микрофон…"; }; state.recognition.onresult = event => { let finalText = state.speechFinalText || ""; let interimText = ""; for (let i = event.resultIndex; i < event.results.length; i += 1) { const transcript = event.results[i][0].transcript.trim(); if (event.results[i].isFinal) finalText += `${finalText ? " " : ""}${transcript}`; else interimText += `${interimText ? " " : ""}${transcript}`; } state.speechFinalText = finalText; $("#speaking-input").value = `${finalText}${finalText && interimText ? " " : ""}${interimText}`; }; state.recognition.onend = () => { if (state.keepListening) { $("#recording-status").textContent = "Запись остаётся включённой. Слушаю…"; setTimeout(() => { if (!state.keepListening) return; try { state.recognition.start(state.micTrack); } catch { try { state.recognition.start(); } catch {} } }, 120); return; } $("#microphone").classList.remove("recording"); $("#record-speaking").textContent = "◉ Начать запись"; state.micStream?.getTracks().forEach(track => track.stop()); state.micStream = null; state.micTrack = null; $("#recording-status").textContent = $("#speaking-input").value ? "Запись остановлена. Нажмите «Проверить ответ»." : "Запись остановлена без распознанной речи."; }; state.recognition.onerror = event => { if (event.error === "no-speech" && state.keepListening) { $("#recording-status").textContent = "Пауза. Запись всё ещё включена — продолжайте говорить."; return; } $("#recording-status").textContent = event.error === "not-allowed" ? "Доступ к микрофону запрещён. Разрешите его в адресной строке браузера и повторите." : "Не получилось распознать речь. Проверьте выбранный микрофон и интернет."; }; }
async function transcribeRecordedAudio(blob) { const response = await fetch("/api/transcribe", { method:"POST", headers:{"Content-Type":blob.type || "audio/webm"}, body:blob }); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.error || "Не удалось распознать аудио."); } return (await response.json()).text; }
function addChatMessage(role, text) { const log = $("#tutor-log"); const message = document.createElement("article"); message.className = `chat-message ${role === "user" ? "user-message" : "tutor-message"}`; message.innerHTML = role === "user" ? `<div><p>${escapeHtml(text)}</p></div>` : `<span class="chat-avatar">✦</span><div><strong>Hoowy.English AI</strong>${paragraphize(text)}</div>`; log.append(message); log.scrollTop = log.scrollHeight; return message; }

function vocabularyTranslation(word, language = state.language) {
  const translation = word.translation || { ru:word.translationRu || "", kz:word.translationKz || "" };
  return language === "kz" ? (translation.kz || translation.ru) : (translation.ru || translation.kz);
}
function vocabularySeries(word) {
  const extras = Array.isArray(word.extras) ? word.extras.map(([name, ru, kz]) => ({ word:name, translation:{ru, kz}, synonyms:[] })) : [];
  const candidates = [...extras, ...words].filter(item => item.word && item.word !== word.word);
  const unique = [];
  [word, ...shuffle(candidates)].forEach(item => { if (!unique.some(entry => entry.word === item.word) && unique.length < 5) unique.push(item); });
  return unique;
}
function buildVocabularyPracticeV2(word) {
  const series = state.vocabularyBatch?.[0]?.word === word.word ? state.vocabularyBatch : vocabularySeries(word);
  state.vocabularyBatch = series;
  const older = words.filter(item => !series.some(entry => entry.word === item.word));
  const fallback = ["library", "bicycle", "garden", "teacher", "journey", "window", "morning", "friend"];
  return shuffle(series).map((target, index) => {
    const useOlder = index === series.length - 1 && older.length && Math.random() < .5;
    const asked = useOlder ? shuffle(older)[0] : target;
    const banned = new Set((asked.synonyms || []).map(value => value.toLowerCase()));
    const askMeaning = index % 2 === 1;
    const distractors = shuffle([...series, ...older]).filter(item => item.word !== asked.word && !banned.has(item.word.toLowerCase()));
    if (askMeaning) {
      const options = shuffle([{ text:vocabularyTranslation(asked), correct:true }, ...distractors.slice(0, 3).map(item => ({ text:vocabularyTranslation(item), correct:false }))]);
      return { question: state.language === "kz" ? `«${asked.word}» сөзі нені білдіреді?` : `Что означает слово «${asked.word}»?`, options, answerLabel: state.language === "kz" ? "Ағылшын сөзінің дұрыс мағынасын таңдаңыз." : "Выбери верное значение английского слова." };
    }
    const wordDistractors = distractors.map(item => item.word);
    fallback.forEach(item => { if (!banned.has(item) && item !== asked.word && !wordDistractors.includes(item)) wordDistractors.push(item); });
    const options = shuffle([{ text:asked.word, correct:true }, ...wordDistractors.slice(0, 3).map(text => ({ text, correct:false }))]);
    return { question: state.language === "kz" ? `Қалай ағылшынша айтылады: «${vocabularyTranslation(asked)}»?` : `Как будет по-английски: «${vocabularyTranslation(asked)}»?`, options, answerLabel: useOlder ? (state.language === "kz" ? "Бұл бұрын өткен сөз. Есте сақтадыңыз!" : "Это слово из предыдущих серий — повторение көмектеседі.") : (state.language === "kz" ? "Тек бір дұрыс жауап бар." : "Среди вариантов только один правильный ответ.") };
  });
}
function renderVocabularyV2() {
  const rawWord = state.currentWord || words[state.wordIndex];
  const word = rawWord.translation ? rawWord : { ...rawWord, translation:{ru:rawWord.translationRu, kz:rawWord.translationKz} };
  const kz = state.language === "kz";
  $("#vocabulary-view").classList.remove("practice-mode");
  $("#learn-word").innerHTML = `${kz ? "5 тапсырманы бастау" : "Начать 5 заданий"} <span>→</span>`;
  $("#word-name").textContent = word.word;
  $("#word-pronunciation").textContent = word.pronunciation || "";
  $("#word-translation").innerHTML = `<strong>${kz ? "Қазақша:" : "Русский:"}</strong> ${escapeHtml(vocabularyTranslation(word))}<small>${kz ? "Орысша" : "Қазақша"}: ${escapeHtml(vocabularyTranslation(word, kz ? "ru" : "kz"))}</small>`;
  $("#word-example").textContent = `“${word.example || ""}”`;
  $("#synonyms").innerHTML = (word.synonyms || []).map(item => `<span>${escapeHtml(item)}</span>`).join("");
  const series = vocabularySeries(word);
  state.vocabularyBatch = series;
  $("#vocabulary-series").innerHTML = series.map(item => `<article><div><b>${escapeHtml(item.word)}</b><span>${escapeHtml(vocabularyTranslation(item))}</span><small>${escapeHtml(item.pronunciation || "Произношение доступно по кнопке")}</small></div><button type="button" class="series-sound" data-series-word="${escapeHtml(item.word)}" aria-label="Прослушать ${escapeHtml(item.word)}">🔊</button></article>`).join("");
  state.vocabularyPractice = buildVocabularyPracticeV2(word);
  state.vocabularyStep = 0;
  renderVocabularyPractice();
}
function setViewV2(name) {
  state.view = name;
  $$(".view").forEach(view => view.classList.toggle("active", view.id === `${name}-view`));
  $$(".nav-link").forEach(button => button.classList.toggle("active", button.dataset.view === name));
  const labels = {home:"Главная",grammar:"Грамматика",vocabulary:"Слова",writing:"Письмо",speaking:"Речь",tutor:"AI-репетитор",progress:"Прогресс"};
  $("#crumb").textContent = tr(labels[name]);
  window.scrollTo({ top:0, behavior:"smooth" });
  if (name === "progress") renderProgress();
  if (["grammar","vocabulary","writing","speaking"].includes(name)) loadExercise(name);
}
function cooldownTarget(kind) { return $(kind === "grammar" ? "#check-grammar" : kind === "vocabulary" ? "#next-vocabulary-task" : kind === "writing" ? "#next-writing" : "#next-speaking"); }
function cooldownTargets(kind) { return kind === "grammar" ? [$("#check-grammar"), $("#next-grammar"), ...$$("#grammar-answers .answer")] : [cooldownTarget(kind)]; }
function cooldownContainer(kind) { return $(kind === "grammar" ? "#grammar-view .question-card" : kind === "vocabulary" ? "#vocabulary-view .quiz-card" : kind === "writing" ? "#writing-view .editor-card" : "#speaking-view .speaking-card"); }
function finishCooldown(kind) {
  if (!state.cooldowns?.[kind]) return;
  delete state.cooldowns[kind];
  state.practiceAttempts ||= {};
  state.practiceAttempts[kind] = 0;
  cooldownTargets(kind).filter(Boolean).forEach(button => { button.disabled = false; button.classList.remove("cooldown-disabled"); });
  if (kind === "grammar") $("#next-grammar").textContent = tr("Другое задание");
  $(`#practice-cooldown-${kind}`)?.remove();
  loadExerciseFromServer(kind);
}
function renderCooldown(kind) {
  const remaining = state.cooldowns?.[kind] - Date.now();
  if (!Number.isFinite(remaining) || remaining <= 0) { finishCooldown(kind); return; }
  const seconds = Math.max(1, Math.ceil(remaining / 1000));
  cooldownTargets(kind).filter(Boolean).forEach(button => { button.disabled = true; button.classList.add("cooldown-disabled"); });
  let note = $(`#practice-cooldown-${kind}`); if (!note) { note = document.createElement("p"); note.id = `practice-cooldown-${kind}`; note.className = "practice-cooldown"; cooldownContainer(kind)?.append(note); }
  note.textContent = state.language === "kz" ? `Жаңа тапсырмалар ${seconds} секундтан кейін ашылады.` : `Новые задания откроются автоматически через ${seconds} сек.`;
}
function startCooldown(kind) {
  state.cooldowns ||= {};
  if (state.cooldowns[kind]) return;
  state.cooldowns[kind] = Date.now() + 40000;
  renderCooldown(kind);
  const timer = setInterval(() => {
    if (!state.cooldowns[kind]) { clearInterval(timer); return; }
    renderCooldown(kind);
  }, 250);
   setTimeout(() => {
     clearInterval(timer);
    finishCooldown(kind);
   }, 40000);
}
function notePractice(kind) { state.practiceAttempts ||= {}; state.practiceAttempts[kind] = (state.practiceAttempts[kind] || 0) + 1; if (state.practiceAttempts[kind] >= 10) startCooldown(kind); }
const loadExerciseFromServer = loadExercise;
buildVocabularyPractice = buildVocabularyPracticeV2;
renderVocabulary = renderVocabularyV2;
setView = setViewV2;
loadExercise = async function(kind) {
  if (state.cooldowns?.[kind]) { renderCooldown(kind); return; }
  const result = await loadExerciseFromServer(kind);
  notePractice(kind);
  return result;
};
const saveProgress = registerProgress;
registerProgress = saveProgress;
function renderSkillStatus(kind) {
  const view = $(`#${kind}-view`); if (!view) return;
  let status = view.querySelector(`.section-skill-status[data-skill="${kind}"]`);
  if (!status) { status = document.createElement("div"); status.className = "section-skill-status"; status.dataset.skill = kind; view.querySelector(".page-title")?.append(status); }
  const names = { grammar:"Грамматика", vocabulary:"Слова", writing:"Письмо", speaking:"Речь" };
  const level = state.taskLevels[kind] || state.progress.skillLevels?.[kind] || "A1";
  const score = Math.max(0, Math.min(100, Number(state.progress.skills?.[kind]) || 0));
  const label = state.language === "kz" ? {grammar:"Грамматика",vocabulary:"Сөздік",writing:"Жазылым",speaking:"Сөйлеу"}[kind] : names[kind];
  status.innerHTML = `<span>${label}: <strong>${level}</strong></span><div class="section-skill-line" role="progressbar" aria-label="${label}: ${score}%" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${score}"><i style="width:${score}%"></i></div><small>${score}%</small>`;
}
function renderAllSkillStatuses() { ["grammar","vocabulary","writing","speaking"].forEach(renderSkillStatus); }
const originalSyncProgressUI = syncProgressUI;
syncProgressUI = function() { originalSyncProgressUI(); renderAllSkillStatuses(); };
const originalShowExercise = showExercise;
showExercise = function(kind, exercise) { originalShowExercise(kind, exercise); renderSkillStatus(kind); };
function naturalnessHint(text) {
  const value = String(text || "").trim();
  const wordsCount = value.split(/\s+/).filter(Boolean).length;
  const repeated = new Set(value.toLowerCase().match(/\b[a-z]{4,}\b/g) || []).size < Math.max(3, wordsCount * .42);
  const templateLike = /in conclusion|moreover|it is important to note|firstly.{0,90}secondly/i.test(value);
  const message = wordsCount < 18 || repeated || templateLike ? "Есть шаблонные или повторяющиеся фрагменты. Добавь личный пример или деталь своими словами." : "Текст выглядит достаточно естественным и разнообразным по структуре.";
  return `<aside class="naturalness-note"><b>Проверка естественности</b><p>${message}</p><small>Это ориентир по стилю, а не доказательство, что текст написал AI или человек.</small></aside>`;
}
const baseSetAiResult = setAiResult;
setAiResult = function(selector, stateName, html) {
  const source = selector === "#writing-result" ? $("#writing-input")?.value : selector === "#speaking-result" ? $("#speaking-input")?.value : "";
  const enhanced = !stateName && source?.trim().split(/\s+/).length >= 5 ? `${html}${naturalnessHint(source)}` : html;
  baseSetAiResult(selector, stateName, enhanced);
};
$("#vocabulary-series")?.addEventListener("click", event => {
  const button = event.target.closest("[data-series-word]"); if (!button || !("speechSynthesis" in window)) return;
  speechSynthesis.cancel(); const voice = new SpeechSynthesisUtterance(button.dataset.seriesWord); voice.lang = "en-US"; voice.rate = .82; speechSynthesis.speak(voice);
});
const writingField = $("#writing-input");
["paste", "drop"].forEach(type => writingField?.addEventListener(type, event => { event.preventDefault(); showToast("Вставка текста отключена: напишите ответ самостоятельно."); }));
writingField?.addEventListener("beforeinput", event => { if (event.inputType === "insertFromPaste" || event.inputType === "insertFromDrop") { event.preventDefault(); showToast("Вставка текста отключена: напишите ответ самостоятельно."); } });
$$(".nav-link").forEach(button => button.addEventListener("click", () => setView(button.dataset.view)));
$$('[data-go]').forEach(button => button.addEventListener("click", () => setView(button.dataset.go)));
async function checkGrammarAnswer() { if (state.selectedGrammar === null || state.grammarChecked) return; state.grammarChecked = true; $("#check-grammar").disabled = true; const task = state.currentGrammar || grammarExercises[state.grammarIndex]; const correct = state.selectedGrammar === task.answer; $$(".answer").forEach((button,index) => { button.disabled = true; const resultClass = index === task.answer ? "correct" : index === state.selectedGrammar ? "incorrect" : ""; if (resultClass) button.classList.add(resultClass); }); $("#grammar-feedback").className = `feedback-card ${correct ? "correct-feedback" : "incorrect-feedback"}`; $("#grammar-feedback").innerHTML = `<span class="feedback-symbol">${correct ? "✓" : "!"}</span><h3>${correct ? (state.language === "kz" ? "Дұрыс! Өте жақсы." : "Верно! Отличная работа.") : (state.language === "kz" ? "Жақын қалдыңыз — талдайық." : "Почти — давай разберём.")}</h3><p><strong>${task.rule || "Grammar"}:</strong> ${task.explanation}</p><ul><li><strong>${state.language === "kz" ? "Мысал" : "Пример"}:</strong> ${task.example || "—"}</li><li>${state.language === "kz" ? "Дұрыс жауап" : "Правильный ответ"}: <strong>${task.options[task.answer]}</strong></li></ul>`; await registerProgress("grammar", correct ? 100 : 35); }
$("#check-grammar").addEventListener("click", checkGrammarAnswer);
$("#next-grammar").addEventListener("click", () => loadExercise("grammar"));
$("#check-vocabulary").addEventListener("click", async () => { if (state.selectedVocab === null || state.vocabularyChecked) return; state.vocabularyChecked = true; $("#check-vocabulary").disabled = true; const practice = state.vocabularyPractice[state.vocabularyStep]; const correct = Boolean(practice.options[state.selectedVocab]?.correct); $$(".mini-answer").forEach((button,index) => { button.disabled = true; if (practice.options[index]?.correct) button.classList.add("selected"); else if (index === state.selectedVocab) button.classList.add("incorrect"); }); $("#vocabulary-feedback").textContent = correct ? (state.language === "kz" ? "Дұрыс! Келесі жаттығуға өтіңіз." : "Верно! Переходи к следующему заданию.") : (state.language === "kz" ? "Дұрыс жауап белгіленді. Келесі тапсырмаға өтіңіз." : "Правильный вариант выделен. Переходи к следующему заданию."); await registerProgress("vocabulary", correct ? 100 : 0); $("#next-vocabulary-task").hidden = false; });
$("#next-vocabulary-task").addEventListener("click", () => { if (state.vocabularyStep < state.vocabularyPractice.length - 1) { state.vocabularyStep += 1; renderVocabularyPractice(); } else { loadExercise("vocabulary"); } });
$("#learn-word").addEventListener("click", () => { $("#vocabulary-view").classList.add("practice-mode"); renderVocabularyPractice(); $("#vocabulary-question").scrollIntoView({behavior:"smooth",block:"center"}); });
$("#next-word")?.addEventListener("click", () => loadExercise("vocabulary"));
$("#next-writing").addEventListener("click", () => loadExercise("writing"));
$$("#writing-modes button").forEach(button => button.addEventListener("click", () => selectWritingType(button.dataset.writingType)));
$$("#writing-feedback-tabs button").forEach(button => button.addEventListener("click", () => { $$("#writing-feedback-tabs button").forEach(entry => entry.classList.toggle("selected", entry === button)); renderWritingFeedback(button.dataset.feedbackTab); }));
$("#next-speaking").addEventListener("click", () => loadExercise("speaking"));
$("#speak-word").addEventListener("click", () => { const word = state.currentWord || words[state.wordIndex]; if (!("speechSynthesis" in window)) { $("#word-pronunciation").textContent = "Аудио не поддерживается в этом браузере."; return; } speechSynthesis.cancel(); const voice = new SpeechSynthesisUtterance(word.word); voice.lang = "en-US"; voice.rate = .82; speechSynthesis.speak(voice); });
$("#writing-input").addEventListener("input", event => { const wordsCount = event.target.value.trim() ? event.target.value.trim().split(/\s+/).length : 0; $("#word-count").textContent = `${wordsCount} / 400 слов`; });
// Прежнее распознавание прямо в браузере. Оно не отправляет звук в TokenWave.
// Обработчик зарегистрирован до нового, поэтому останавливает его выполнение.
$("#record-speaking").addEventListener("click", async event => { event.stopImmediatePropagation(); if (state.keepListening) { state.keepListening = false; try { state.recognition?.stop(); } catch {} return; } try { $("#recording-status").textContent = "Подключаю выбранный микрофон…"; await prepareMicrophone(); initSpeakingRecognition(); state.speechFinalText = ""; $("#speaking-input").value = ""; state.keepListening = true; state.recognition.start(); } catch (error) { state.keepListening = false; $("#recording-status").textContent = error?.name === "NotAllowedError" ? "Доступ к микрофону запрещён. Разрешите его в браузере и повторите." : error.message || "Не удалось включить распознавание речи."; } });
$("#analyze-writing").addEventListener("click", async () => { const text = $("#writing-input").value.trim(); if (text.split(/\s+/).filter(Boolean).length < 8) { setAiResult("#writing-result", "", `<span class="feedback-symbol">!</span><h3>Нужно немного больше текста</h3><p>Напишите хотя бы 8 слов на английском, чтобы анализ был полезным.</p>`); return; } setAiResult("#writing-result", "loading", `<span class="feedback-symbol">✦</span><h3>AI читает ваш текст…</h3><p>Проверяю грамматику, словарь, структуру и ясность мысли.</p>`); try { const answer = await askAi(`Ты — доброжелательный преподаватель английского для школьника уровня ${state.level}. Формат задания: ${state.writingType}. Проверь текст ученика. Отвечай только на русском. Сначала дай 2 сильные стороны. Затем перечисли до 5 ошибок в формате «исходный фрагмент → исправление — короткое объяснение». В конце дай улучшенную версию 1–2 предложений и отдельной последней строкой напиши строго: «Оценка уровня: N/100». Не переписывай весь текст. Текст: ${text}`); state.writingFeedback = answer; renderWritingFeedback("review"); await registerProgress("writing", scoreFromFeedback(answer)); } catch (error) { setAiResult("#writing-result", "", `<span class="feedback-symbol">!</span><h3>Не удалось получить AI-отзыв</h3><p>${escapeHtml(error.message)} Войдите в учебный аккаунт и повторите попытку.</p>`); } });
$("#record-speaking").addEventListener("click", async () => { if (state.keepListening) { state.keepListening = false; state.mediaRecorder?.stop(); return; } try { $("#recording-status").textContent = "Подключаю выбранный микрофон…"; await prepareMicrophone(); if (!window.MediaRecorder) throw new Error("Этот браузер не поддерживает запись аудио. Откройте сайт в Chrome или Edge."); const mimeType = ["audio/webm;codecs=opus","audio/webm","audio/ogg"].find(type => MediaRecorder.isTypeSupported(type)); state.audioChunks = []; state.mediaRecorder = new MediaRecorder(state.micStream, mimeType ? { mimeType } : undefined); state.mediaRecorder.ondataavailable = event => { if (event.data.size) state.audioChunks.push(event.data); }; state.mediaRecorder.onstart = () => { $("#microphone").classList.add("recording"); $("#record-speaking").textContent = "■ Остановить запись"; $("#recording-status").textContent = "Запись идёт. Говори по-английски, затем нажми «Остановить запись»."; }; state.mediaRecorder.onstop = async () => { $("#microphone").classList.remove("recording"); $("#record-speaking").textContent = "◉ Начать запись"; const audio = new Blob(state.audioChunks, { type:state.mediaRecorder.mimeType || "audio/webm" }); state.micStream?.getTracks().forEach(track => track.stop()); state.micStream = null; state.micTrack = null; if (audio.size < 300) { $("#recording-status").textContent = "Запись слишком короткая. Попробуйте ещё раз."; return; } try { $("#recording-status").textContent = "gpt-4o-transcribe расшифровывает запись…"; $("#speaking-input").value = await transcribeRecordedAudio(audio); $("#recording-status").textContent = "Речь распознана. Нажмите «Проверить ответ»."; } catch (error) { $("#recording-status").textContent = error.message; } }; $("#speaking-input").value = ""; state.keepListening = true; state.mediaRecorder.start(1000); } catch (error) { state.keepListening = false; $("#recording-status").textContent = error?.name === "NotAllowedError" ? "Доступ к микрофону запрещён. Разрешите его в браузере и повторите." : error.message || "Не удалось включить микрофон."; } });
$("#check-speaking").addEventListener("click", async () => { const text = $("#speaking-input").value.trim(); if (text.split(/\s+/).filter(Boolean).length < 5) { setAiResult("#speaking-result", "", `<span class="feedback-symbol">!</span><h3>Добавьте немного больше</h3><p>Ответьте как минимум одним полным предложением на английском.</p>`); return; } setAiResult("#speaking-result", "loading", `<span class="feedback-symbol">✦</span><h3>AI готовит feedback…</h3><p>Оцениваю смысл, грамматику, словарь и естественность речи.</p>`); try { const answer = await askAi(`Ты — дружелюбный AI-репетитор английского для школьника уровня ${state.level}. Ученик ответил на вопрос «${$("#speaking-question").textContent}»: «${text}». Дай feedback только на русском, коротко: 1) что удалось, 2) до 3 исправлений с объяснением, 3) один естественный вариант фразы, 4) совет для следующего ответа. Не критикуй произношение, потому что у тебя есть только текст. В конце отдельной строкой напиши строго: «Оценка уровня: N/100».`); setAiResult("#speaking-result", "", `<span class="feedback-symbol">✓</span><h3>AI Feedback</h3>${paragraphize(answer)}`); await registerProgress("speaking", scoreFromFeedback(answer)); } catch (error) { setAiResult("#speaking-result", "", `<span class="feedback-symbol">!</span><h3>AI пока недоступен</h3><p>${escapeHtml(error.message)}</p>`); } });
$("#tutor-form").addEventListener("submit", async event => { event.preventDefault(); const input = $("#tutor-input"); const prompt = input.value.trim(); if (!prompt) return; addChatMessage("user", prompt); input.value = ""; const loading = addChatMessage("assistant", "Думаю над объяснением…"); try { const answer = await askAi(`Ты — Hoowy.English, AI-репетитор английского для школьников 13–18 лет. Уровень ученика: ${state.level}. Объясняй на русском, но английские примеры сохраняй на английском. Отвечай понятно, с коротким правилом, 2–3 примерами и в конце предложи маленькое упражнение. Не выдумывай результаты и не называй себя ChatGPT. Вопрос ученика: ${prompt}`); loading.remove(); addChatMessage("assistant", answer); } catch (error) { loading.remove(); addChatMessage("assistant", `AI Tutor пока недоступен: ${error.message}`); } });
$("#tutor-file").addEventListener("change", async event => {
  const file = event.target.files?.[0]; const status = $("#tutor-attachment-status");
  if (!file) return;
  if (file.size > 10 * 1024 * 1024) { status.textContent = "Файл больше 10 МБ. Выберите файл меньшего размера."; event.target.value = ""; return; }
  status.textContent = `Распознаю текст: ${file.name}…`;
  const form = new FormData(); form.append("file", file);
  try {
    if (isGitHubPages) throw new Error("Распознавание файлов доступно в полной версии сайта с Node.js API.");
    const response = await fetch("/api/tutor-file", { method:"POST", body:form });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || "Не удалось распознать файл.");
    const text = String(data.text || "").trim();
    $("#tutor-input").value = `Проверь и объясни этот текст:\n${text}`;
    status.textContent = `✓ Текст из «${data.fileName || file.name}» распознан. Можешь отредактировать вопрос и нажать отправку.`;
  } catch (error) { status.textContent = error.message || "Не удалось распознать файл."; }
  finally { event.target.value = ""; }
});
$$('[data-prompt]').forEach(button => button.addEventListener("click", () => { setView("tutor"); $("#tutor-input").value = button.dataset.prompt; $("#tutor-input").focus(); }));
$("#language-toggle").addEventListener("click", () => applyLanguage(state.language === "ru" ? "kz" : "ru"));
const themeToggle = $("#theme-toggle");
function applyTheme(theme) { const dark = theme === "dark"; document.body.classList.toggle("dark-theme", dark); themeToggle.textContent = dark ? "☼" : "◐"; themeToggle.title = dark ? "Светлая тема" : "Тёмная тема"; localStorage.setItem("hoowy-english-theme", dark ? "dark" : "light"); }
themeToggle.addEventListener("click", () => applyTheme(document.body.classList.contains("dark-theme") ? "light" : "dark"));
applyTheme(localStorage.getItem("hoowy-english-theme") || "light");
const profileDialog = $("#profile-dialog");
function showProfileDialog() { const profile = state.progress.profile || {}; $("#profile-name").value = profile.name || "Ученик"; state.pendingAvatar = profile.avatar || "А"; state.pendingAvatarImage = ""; state.usePresetAvatar = false; $("#avatar-upload").value = ""; $$("#avatar-options button").forEach(button => button.classList.toggle("selected", button.dataset.avatar === state.pendingAvatar)); renderProfilePreview(state.pendingAvatar); profileDialog.showModal(); }
[$("#profile-button"),$("#top-avatar")].forEach(button => button.addEventListener("click", showProfileDialog));
$$("#avatar-options button").forEach(button => button.addEventListener("click", () => { state.pendingAvatar = button.dataset.avatar; state.pendingAvatarImage = ""; state.usePresetAvatar = true; $$("#avatar-options button").forEach(entry => entry.classList.toggle("selected", entry === button)); renderProfilePreview(state.pendingAvatar); }));
$("#avatar-upload").addEventListener("change", event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { alert("Выберите изображение до 10 МБ."); event.target.value = ""; return; } const reader = new FileReader(); reader.onload = () => { state.pendingAvatarImage = String(reader.result); state.usePresetAvatar = false; renderProfilePreview(state.pendingAvatar); }; reader.readAsDataURL(file); });
$("#profile-form").addEventListener("submit", async event => { if (event.submitter?.value !== "save") return; event.preventDefault(); const avatarChanged = Boolean(state.pendingAvatarImage || state.usePresetAvatar); if (!isGitHubPages) { const response = await fetch("/api/profile", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ name:$("#profile-name").value, avatar:state.pendingAvatar }) }); if (!response.ok) return; state.progress = (await response.json()).progress; } else { state.progress.profile = { name:$("#profile-name").value || "Ученик", avatar:state.pendingAvatar || "А" }; localStorage.setItem("fluentpath-progress", JSON.stringify(state.progress)); } if (state.pendingAvatarImage) localStorage.setItem("fluentpath-avatar-image", state.pendingAvatarImage); else if (state.usePresetAvatar) localStorage.removeItem("fluentpath-avatar-image"); state.pendingAvatarImage = ""; syncProgressUI(); profileDialog.close("save"); showToast(avatarChanged ? "Аватарка успешно изменена" : "Профиль успешно изменён"); });
$("#sign-out").addEventListener("click", async () => { localStorage.removeItem("fluentpath-avatar-image"); if (!isGitHubPages) { const response = await fetch("/api/profile", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ name:"Ученик", avatar:"А" }) }); if (response.ok) state.progress = (await response.json()).progress; } else { state.progress.profile = { name:"Ученик", avatar:"А" }; localStorage.setItem("fluentpath-progress", JSON.stringify(state.progress)); } syncProgressUI(); profileDialog.close("signout"); });
function setSidebar(open) { document.querySelector(".app-shell").classList.toggle("sidebar-collapsed", !open); $("#sidebar-open").classList.toggle("visible", !open); localStorage.setItem("fluentpath-sidebar-open", open ? "1" : "0"); }
$("#sidebar-close").addEventListener("click", () => setSidebar(false)); $("#sidebar-open").addEventListener("click", () => setSidebar(true)); setSidebar(localStorage.getItem("fluentpath-sidebar-open") !== "0");

applyLanguage(state.language); getProgress();
